package org.applab.ledgerlink.domain.model;

/**
 * Created by Moses on 7/5/13.
 */
class MeetingAttendance {
    private int attendanceId;
    private Meeting meeting;
    private Member member;
    private boolean isPresent;

    public boolean isPresent() {
        return isPresent;
    }

    public void setPresent(boolean present) {
        isPresent = present;
    }

    public int getAttendanceId() {
        return attendanceId;
    }

    public void setAttendanceId(int attendanceId) {
        this.attendanceId = attendanceId;
    }

    public Meeting getMeeting() {
        return meeting;
    }

    public void setMeeting(Meeting meeting) {
        this.meeting = meeting;
    }

    public Member getMember() {
        return member;
    }

    public void setMember(Member member) {
        this.member = member;
    }

    public MeetingAttendance(){

    }

    public MeetingAttendance(int attendanceId, Meeting meeting, Member member, boolean isPresent) {
        this.attendanceId = attendanceId;
        this.meeting = meeting;
        this.member = member;
        this.isPresent = isPresent;
    }

    public MeetingAttendance(Meeting meeting, Member member, boolean isPresent) {
        //AttendanceSchema ID will be generated by the DB
        this.meeting = meeting;
        this.member = member;
        this.isPresent = isPresent;
    }
}
